# Spatial covariates are passed to the function as a SpatialPixelDataFrame
spatialcovariates <- as(covar_stack, "SpatialPixelsDataFrame")

# Should the model be a marked point process
marks <-  FALSE

# Assumed distribution of the marks
markfamily = 'gaussian'

# Which marks should me included in the model
inclmarks = NULL

# Name of column used if multiple species are implmented in the model
## I interpret this as "name of the column that contains species info" 
speciespresence = "Species"

# A vector of which species should be included in the model
## Which species are we modelling?
inclspecies <- "RedDeer"

# Vector of the names of the coordinates used in datasets. Defaults to \code{c('X','Y')} (For now should be standardized)
coords = c('X','Y')

# Name for the response variable for the presence only datasets
poresp = "PO"

# Name for the response variable for the presence absence datasets
paresp = "PA"

# Names of column of number of columns in observs. 
## WHAAAT. Could use this to specify different years of survey, even if some don't repeat? 
trialname= NULL

# Should coordinates be used in data
## Not sure what this means! 
inclcoords = FALSE

# An inla.mesh object
mesh <- mesh0

# List of mesh parameters
## Either mesh or this has to be specified. If this is specified, the mesh will be generated by the function using this parameters 
meshpars = NULL

# Integration points
## Will be calculated by the function if not provided 
ips = NULL

# Polygon of boundary for region, of class Polygon
## We'd better provide it, otherwise it'll draw it itself and we've simplified and buffered! 
bdry  <-  SpatialPolygons(in_bound@polygons)

# Projection to use if data is not a projection
## This should not be necessary, since our data is projected, but just in case 
proj  <-  CRS("+proj=tmerc +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=km +no_defs")

# Boolean: should predictions (on the linear scale) be made?
##  Not sure what this is about, let's leave the default (FALSE) for now. 
predictions = FALSE

# Should residuals for each dataset be calculated
residuals = TRUE

# Include joint intercept in the model
# Include individual intercepts for each dataset in the model
## not sure about the difference between these two, but let's leave the default options
intercept = FALSE
indivintercepts = TRUE

# Should spatial effects be used for the points in the model
## I guess this is asking if we want a SPDE model for our point data???? 
pointsspatial = TRUE

# Should spatial effects be used for the marks in the model
## I guess this is asking if we want a SPDE model for the marks???? Since we don't have marks, we'll set it to false
marksspatial = FALSE 

# A bru_options options object or a list of options passed on to bru_options()
## https://rdrr.io/github/inlabru-org/inlabru/man/bru_options.html 
options = list()

# Formula given to the presence only datasets
## If we leave the null default the model should construct it on itself
poformula = NULL 

# Formula given to the presence absence datasets
## If we leave the null default the model should construct it on itself
paformula = NULL 

# Tolerance parameter for SpatialPixelsDataFrame
## this has to have a value to construct covariates, but still not sure why
tol = 0
